import { User, VacationRequest, VacationBalance, NewsArticle, Department, ChatMessage } from "@/types";

export const mockDepartments: Department[] = [
  { id: "dept-hr", name: "HR", headId: "usr-001", color: "bg-purple-100 text-purple-700 border-purple-200" },
  { id: "dept-marketing", name: "Marketing", headId: "usr-002", color: "bg-pink-100 text-pink-700 border-pink-200" },
  { id: "dept-dev", name: "Entwicklung", headId: "usr-003", color: "bg-blue-100 text-blue-700 border-blue-200" },
  { id: "dept-sales", name: "Vertrieb", headId: "usr-004", color: "bg-green-100 text-green-700 border-green-200" },
];

export const mockUsers: User[] = [
  {
    id: "usr-001",
    email: "admin@hellbeck.de",
    firstName: "Patrick",
    lastName: "Sagemüller",
    position: "HR-Administrator",
    department: "HR",
    role: "admin",
    phone: "+49 170 1234567",
    street: "Musterstraße 1",
    city: "München",
    zipCode: "80331",
    country: "Deutschland",
    birthDate: "1985-03-20",
    startDate: "2019-01-15",
    isActive: true,
  },
  {
    id: "usr-002",
    email: "anna.schmidt@hellbeck.de",
    firstName: "Anna",
    lastName: "Schmidt",
    position: "Marketing-Leiterin",
    department: "Marketing",
    role: "autor",
    phone: "+49 170 2345678",
    street: "Beispielweg 5",
    city: "München",
    zipCode: "80333",
    country: "Deutschland",
    birthDate: "1992-07-12",
    startDate: "2022-04-01",
    managerId: "usr-001",
    isActive: true,
  },
  {
    id: "usr-003",
    email: "max.mustermann@hellbeck.de",
    firstName: "Max",
    lastName: "Mustermann",
    position: "Teamleiter Entwicklung",
    department: "Entwicklung",
    role: "benutzer",
    phone: "+49 170 3456789",
    street: "Musterstraße 42",
    city: "München",
    zipCode: "80331",
    country: "Deutschland",
    birthDate: "1990-05-15",
    startDate: "2021-03-01",
    managerId: "usr-001",
    isActive: true,
  },
  {
    id: "usr-004",
    email: "clara.fischer@hellbeck.de",
    firstName: "Clara",
    lastName: "Fischer",
    position: "Vertriebsleiterin",
    department: "Vertrieb",
    role: "benutzer",
    phone: "+49 170 4567890",
    street: "Verkaufsstraße 10",
    city: "München",
    zipCode: "80335",
    country: "Deutschland",
    birthDate: "1994-11-03",
    startDate: "2023-06-15",
    managerId: "usr-001",
    isActive: true,
  },
  {
    id: "usr-005",
    email: "ben.wagner@hellbeck.de",
    firstName: "Ben",
    lastName: "Wagner",
    position: "Junior Developer",
    department: "Entwicklung",
    role: "benutzer",
    phone: "+49 170 5678901",
    street: "Codeweg 7",
    city: "München",
    zipCode: "80336",
    country: "Deutschland",
    birthDate: "1998-02-28",
    startDate: "2026-02-01",
    managerId: "usr-003",
    isActive: true,
  },
  {
    id: "usr-006",
    email: "eva.klein@hellbeck.de",
    firstName: "Eva",
    lastName: "Klein",
    position: "HR-Managerin",
    department: "HR",
    role: "autor",
    phone: "+49 170 6789012",
    street: "Personalstraße 3",
    city: "München",
    zipCode: "80337",
    country: "Deutschland",
    birthDate: "1991-09-18",
    startDate: "2020-08-01",
    managerId: "usr-001",
    isActive: true,
  },
];

// Backwards-compatible default user
export const mockUser: User = mockUsers[0];

export const mockVacationBalance: VacationBalance = {
  total: 30,
  used: 12,
  planned: 5,
  remaining: 13,
};

export const mockVacationRequests: VacationRequest[] = [
  {
    id: "vac-001",
    userId: "usr-001",
    startDate: "2026-03-15",
    endDate: "2026-03-22",
    days: 5,
    type: "urlaub",
    status: "genehmigt",
    createdAt: "2026-01-10",
    approvedBy: "usr-001",
    approvedAt: "2026-01-11",
  },
  {
    id: "vac-002",
    userId: "usr-005",
    startDate: "2026-06-01",
    endDate: "2026-06-14",
    days: 10,
    type: "urlaub",
    status: "ausstehend",
    reason: "Sommerurlaub",
    createdAt: "2026-02-01",
  },
  {
    id: "vac-003",
    userId: "usr-006",
    startDate: "2026-01-05",
    endDate: "2026-01-06",
    days: 2,
    type: "sonderurlaub",
    status: "genehmigt",
    reason: "Umzug",
    createdAt: "2025-12-20",
    approvedBy: "usr-001",
    approvedAt: "2025-12-21",
  },
  {
    id: "vac-004",
    userId: "usr-003",
    startDate: "2026-04-10",
    endDate: "2026-04-18",
    days: 7,
    type: "urlaub",
    status: "ausstehend",
    reason: "Osterurlaub",
    createdAt: "2026-02-10",
  },
  {
    id: "vac-005",
    userId: "usr-002",
    startDate: "2026-05-01",
    endDate: "2026-05-05",
    days: 3,
    type: "urlaub",
    status: "ausstehend",
    createdAt: "2026-02-12",
  },
];

export const mockNews: NewsArticle[] = [
  {
    id: "news-001",
    title: "Neue Büroräume im 3. OG eröffnet",
    excerpt:
      "Ab sofort stehen im dritten Obergeschoss moderne Arbeitsplätze und neue Meetingräume zur Verfügung.",
    content:
      "Wir freuen uns, die Eröffnung unserer neuen Büroräume im dritten Obergeschoss bekanntzugeben. Die Räume wurden komplett modernisiert und bieten flexible Arbeitsplätze, drei neue Meetingräume mit modernster Technik sowie eine gemütliche Lounge-Ecke für informelle Gespräche.",
    author: "Geschäftsführung",
    category: "unternehmen",
    publishedAt: "2026-02-08",
    likes: ["usr-002", "usr-003", "usr-005"],
  },
  {
    id: "news-002",
    title: "Teambuilding-Event am 28. Februar",
    excerpt:
      "Gemeinsames Teambuilding-Event mit spannenden Aktivitäten — meldet euch jetzt an!",
    content:
      "Am 28. Februar findet unser großes Teambuilding-Event statt. Auf dem Programm stehen Escape Rooms, Kochkurse und ein gemeinsames Abendessen. Die Teilnahme ist freiwillig und kostenlos. Bitte meldet euch bis zum 20. Februar über das HR-Portal an.",
    author: "HR-Team",
    category: "event",
    publishedAt: "2026-02-05",
    likes: ["usr-001", "usr-004", "usr-006", "usr-002"],
  },
  {
    id: "news-003",
    title: "Willkommen im Team: 5 neue Kolleg:innen",
    excerpt:
      "Diesen Monat begrüßen wir fünf neue Teammitglieder in verschiedenen Abteilungen.",
    content:
      "Wir heißen herzlich willkommen: Anna Schmidt (Marketing), Ben Wagner (Entwicklung), Clara Fischer (Vertrieb), David Bauer (Design) und Eva Klein (HR). Wir freuen uns auf die Zusammenarbeit!",
    author: "HR-Team",
    category: "team",
    publishedAt: "2026-02-03",
    likes: ["usr-005"],
  },
  {
    id: "news-004",
    title: "Neue Regelung: Hybrid-Arbeit ab März",
    excerpt:
      "Ab März 2026 gilt die neue Hybrid-Arbeitsregelung mit 3 Tagen Office und 2 Tagen Remote.",
    content:
      "Nach erfolgreicher Evaluierung unseres Pilotprojekts führen wir ab März die Hybrid-Arbeitsregelung für alle Abteilungen ein. Die Regelung sieht 3 Office-Tage (Dienstag bis Donnerstag) und 2 Remote-Tage (Montag und Freitag) vor.",
    author: "Geschäftsführung",
    category: "hr",
    publishedAt: "2026-01-28",
    likes: ["usr-001", "usr-002", "usr-003", "usr-004", "usr-005", "usr-006"],
  },
  {
    id: "news-005",
    title: "Jahresrückblick 2025 — Rekordumsatz erreicht",
    excerpt:
      "2025 war ein erfolgreiches Jahr mit einem Umsatzwachstum von 23% gegenüber dem Vorjahr.",
    content:
      "Wir blicken auf ein herausragendes Jahr 2025 zurück. Dank des Einsatzes aller Mitarbeitenden konnten wir unseren Umsatz um 23% steigern und zahlreiche neue Kunden gewinnen. Ein besonderer Dank gilt allen Teams für ihren außergewöhnlichen Einsatz!",
    author: "Geschäftsführung",
    category: "unternehmen",
    publishedAt: "2026-01-15",
    likes: ["usr-001", "usr-003"],
  },
];

export const mockChatMessages: ChatMessage[] = [
  {
    id: "msg-001",
    senderId: "usr-003",
    receiverId: "usr-005",
    content: "Hey Ben, hast du das Deployment für heute fertig?",
    timestamp: "2026-02-13T09:15:00",
    read: true,
  },
  {
    id: "msg-002",
    senderId: "usr-005",
    receiverId: "usr-003",
    content: "Hi Max, bin gerade dran. Sollte in einer Stunde fertig sein.",
    timestamp: "2026-02-13T09:18:00",
    read: true,
  },
  {
    id: "msg-003",
    senderId: "usr-003",
    receiverId: "usr-005",
    content: "Super, danke dir! Sag Bescheid, wenn du Hilfe brauchst.",
    timestamp: "2026-02-13T09:20:00",
    read: false,
  },
  {
    id: "msg-004",
    senderId: "usr-001",
    receiverId: "usr-006",
    content: "Eva, kannst du den neuen Mitarbeiter onboarden?",
    timestamp: "2026-02-13T10:00:00",
    read: true,
  },
  {
    id: "msg-005",
    senderId: "usr-006",
    receiverId: "usr-001",
    content: "Klar, mache ich morgen. Ist alles vorbereitet.",
    timestamp: "2026-02-13T10:05:00",
    read: false,
  },
  {
    id: "msg-006",
    senderId: "usr-002",
    receiverId: "usr-001",
    content: "Patrick, die neue Kampagne ist online. Kannst du die News dazu freigeben?",
    timestamp: "2026-02-12T16:30:00",
    read: true,
  },
];
